LOAD DATABASE
     FROM mysql://root:root@mysql_temp/casonreir_mysql
     INTO postgresql://user_admin:password_secret@db/casonreir

 WITH include drop, create tables, create indexes, reset sequences, foreign keys, quote identifiers

 CAST type datetime to timestamptz,
      type tinyint to boolean,
      type int with extra auto_increment to serial

 ALTER SCHEMA 'casonreir_mysql' RENAME TO 'public'

 SET search_path to 'public';
